services:
  web:
    container_name: web
    build: ./core
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ADMIN_USER=${DJANGO_ADMIN_USER}
      - DJANGO_ADMIN_MAIL=${DJANGO_ADMIN_MAIL}
      - DJANGO_ADMIN_PASSWORD=${DJANGO_ADMIN_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/code
    depends_on:
      - db
    networks:
      - webnet
    hostname: web

  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - webnet
    hostname: db

  nginx:
    container_name: nginx
    build:
      context: ./core/www
      dockerfile: Dockerfile
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - SSL_CN=${SSL_CN}
    depends_on:
      - web
    ports:
      - "443:443"
    volumes:
      - ./core/www:/usr/share/nginx/html
    networks:
      - webnet
    hostname: nginx

volumes:
  postgres_data:

networks:
  webnet: